version: '3'

services:
  startuplink-web:
    build: .
    image: dliakhov/startuplink-web:latest
    container_name: "startuplink-web"
    hostname: "startuplink-web"
    restart: always
    ports:
      - "8080:8080"

    volumes:
      - ./var:/backend/var
    environment:
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_DOMAIN
      - AUTH0_CALLBACK_URL=http://localhost:8080/callback
      - PORT=8080
      - STORE_BOLT_DB=/backend/var/store
      - TIMEOUT=600
    healthcheck:
      test: curl --fail -s http://localhost:8080/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
