version: '3'

services:
  startuplink-web:
    build: .
    image: dliakhov/startuplink-web:latest
    container_name: "startuplink-web"
    hostname: "startuplink-web"
    restart: always
    ports:
      - "8080:8080"

    volumes:
      - ./var:/backend/var
    env_file:
      - .env.local
    healthcheck:
      test: curl --fail -s http://localhost:8080/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
