GET {{url}}/admin/api/all-data
Authorization: Basic admin password

###
GET {{url}}/admin/api/all-data
Authorization: Basic {{user}} {{adminPassword}}

###
GET {{url}}/admin/api/export-db
Authorization: Basic {{user}} {{adminPassword}}
