name: build

on:
  pull_request:


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.41.1
          args: --disable-all --tests=false --enable=unconvert --enable=megacheck --enable=structcheck --enable=gas --enable=gocyclo --enable=dupl --enable=misspell --enable=unparam --enable=varcheck --enable=deadcode --enable=typecheck  --enable=ineffassign --enable=varcheck
          skip-go-installation: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
      - name: build and test backend
        run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
