name: build

on:
  push:
    branches:
    tags:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: build and test backend
        run: |
          cd app
          go test -mod=vendor -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.20.0
          go get -u github.com/mattn/goveralls

      - name: run backend linters
        run: |
          cd backend
          $GITHUB_WORKSPACE/golangci-lint run --out-format=tab --disable-all --tests=false --enable=unconvert \
            --enable=megacheck --enable=structcheck --enable=gas --enable=gocyclo --enable=dupl --enable=misspell \
            --enable=unparam --enable=varcheck --enable=deadcode --enable=typecheck \
            --enable=ineffassign --enable=varcheck ./... ;
