name: Publish Docker
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build docker image
        run: |
          docker build . --tag aemdeveloper/startuplink-web-go:$(date +'%Y-%m-%d')-$(GITHUB_SHA::8)
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "{{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push aemdeveloper/startuplink-web-go:$(date +'%Y-%m-%d')-$(GITHUB_SHA::8)

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker volume create boltdb_store
            if [ $(docker ps | grep ${{ secrets.CONTAINER_NAME }} | wc -l) -gt 0 ]
            then
              docker stop ${{ secrets.CONTAINER_NAME }}
              docker rm --force ${{ secrets.CONTAINER_NAME }}
              echo "Container stopped"
            fi
            docker run -d -e AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} \
              --name ${{ secrets.CONTAINER_NAME }} \
              -e AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} \
              -e AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }} \
              -e STORE_BOLT_DB=/backend/var/store \
              -e AUTH0_CALLBACK_URL=${{ secrets.HOST_DOMAIN }}/callback \
              -e PROFILE=local \
              -v boltdb_store:/backend/var/store \
              -p 80:8080 aemdeveloper/startuplink-web-go:$(date +'%Y-%m-%d')-$(GITHUB_SHA::8)
