name: Publish Docker
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build docker image
        run: docker build .

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: aemdeveloper/startuplink-web-go
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker volume create boltdb_store
            if [ $(docker ps | grep startupLinkWeb | wc -l) -gt 0 ]
            then
              docker stop startupLinkWeb
              echo "Container stopped"
            fi
            docker run -d -e AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} \
              --name startupLinkWeb \
              -e AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} \
              -e AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }} \
              -e STORE_BOLT_DB=/backend/var/store \
              -e AUTH0_CALLBACK_URL=${{ secrets.HOST_DOMAIN }}/callback \
              -e PROFILE=local \
              -v boltdb_store:/backend/var/store \
              -p 80:8080 aemdeveloper/startuplink-web-go:latest
